server:
  port: 9877
  
#配置eureka注册中心集群
eureka:
  client:
    service-url:
      defaultZone: http://192.168.207.165:9822/eureka,http://192.168.207.165:9823/eureka

##Spring基本配置
spring:
  #zipkin链路跟踪地址
  zipkin:
    base-url: http://192.168.207.165:9889
 
##选择需要对外暴露的路径
management:
  endpoints:
    web: 
      exposure: 
        include: '*'